<?php
$categoryMap=['cpu'=>'cpu','motherboard'=>'motherboard','gpu'=>'gpu','ram'=>'ram','storage'=>'storage','psu'=>'psu','case'=>'case','cooling'=>'cooling'];
$groups=[]; foreach($categoryMap as $key=>$slug) $groups[$key]=array_values(array_filter($products,fn($p)=>strtolower($p['category_name'])===$slug || ($key==='motherboard'&&strtolower($p['category_name'])==='motherboard')));
$slots=[['memory','CPU','cpu'],['developer_board','Mainboard','motherboard'],['videogame_asset','Graphic Card','gpu'],['view_module','RAM','ram'],['database','Storage','storage'],['bolt','Power Supply','psu'],['inventory_2','Case','case'],['toys','Cooling','cooling'],['monitor','Monitor',null]];
?>
<section class="container page spec-workspace"><div class="spec-title"><div><span class="eyebrow">USED-PC SPEC BUILDER · PARTIAL</span><h1>จัดสเปกคอมมือสอง</h1><p>เลือกรุ่นทีละชิ้น ระบบจะใช้เฉพาะข้อมูลราคาที่ผ่านการตรวจแล้ว</p></div><span class="draft-pill"><span class="material-symbols-outlined">verified</span> ตรวจข้อมูลแล้วเท่านั้น</span></div>
<?php foreach($errors as $error): ?><div class="alert"><?= htmlspecialchars($error) ?></div><?php endforeach; ?>
<?php if($result): ?>
<div class="saved-build card"><div class="section-head"><div><span class="meta">BUILD <?= htmlspecialchars(substr($result['uuid'],0,8)) ?></span><h2>สเปกที่บันทึกแล้ว</h2></div><a class="button ghost" href="<?= $base ?>/build">จัดสเปกใหม่</a></div>
<?php foreach($result['items'] as $item): ?><div class="build-item"><div><span class="meta"><?= htmlspecialchars($item['component_role']) ?></span><b><?= htmlspecialchars($item['full_name']) ?></b><small>Confidence <?= number_format((float)$item['confidence_score']) ?>%</small></div><span>฿<?= number_format((float)$item['price_low']) ?>–<?= number_format((float)$item['price_high']) ?></span></div><?php endforeach; ?>
<div class="build-totals"><div><small>ต่ำ</small><b>฿<?= number_format((float)$result['estimated_low']) ?></b></div><div><small>คาดการณ์</small><b>฿<?= number_format((float)$result['estimated_expected']) ?></b></div><div><small>สูง</small><b>฿<?= number_format((float)$result['estimated_high']) ?></b></div></div><div class="notice"><?= htmlspecialchars($result['compatibility_notes']) ?></div></div>
<?php else: ?>
<form method="post" action="<?= $base ?>/build" id="spec-builder-form"><input type="hidden" name="_token" value="<?= \App\Core\Csrf::token() ?>">
<div class="spec-controls card"><label>งบประมาณ <div class="budget-input"><span>฿</span><input id="spec-budget" type="number" name="budget" min="5000" max="500000" step="500" value="<?= htmlspecialchars((string)($old['budget']??25000)) ?>" required></div></label><label>ใช้สำหรับ<select name="intended_use"><option value="gaming">Gaming</option><option value="work">Work</option><option value="streaming">Streaming</option><option value="office">Office</option><option value="ai">AI</option></select></label><label>ความละเอียด<select name="resolution"><option value="1080p">1080p</option><option value="1440p">1440p</option><option value="4k">4K</option><option value="none">ไม่เกี่ยวข้อง</option></select></label><label>รูปแบบ<select name="mix_preference"><option value="used">มือสองเป็นหลัก</option><option value="mixed">ใหม่ + มือสอง</option><option value="new">ของใหม่เป็นหลัก</option></select></label></div>
<div class="spec-layout">
<aside class="component-nav card"><?php foreach($slots as $index=>$slot): ?><a href="#slot-<?= $index ?>" class="<?= $slot[2]?'available':'disabled' ?>"><span class="material-symbols-outlined"><?= $slot[0] ?></span><span><b><?= $slot[1] ?></b><small><?= $slot[2]?'มีข้อมูลราคา':'รอข้อมูล' ?></small></span><i class="material-symbols-outlined"><?= $slot[2]?'chevron_right':'lock' ?></i></a><?php endforeach; ?></aside>
<main class="component-picker">
<?php foreach($slots as $index=>$slot): ?><section id="slot-<?= $index ?>" class="component-section card"><div class="component-head"><div><span class="material-symbols-outlined"><?= $slot[0] ?></span><div><span class="meta">COMPONENT <?= str_pad((string)($index+1),2,'0',STR_PAD_LEFT) ?></span><h2><?= $slot[1] ?></h2></div></div><span class="badge"><?= $slot[2] ? count($groups[$slot[2]]) . ' รุ่น' : 'ยังไม่มีข้อมูล' ?></span></div>
<?php if($slot[2]): ?><?php $brands=array_values(array_unique(array_column($groups[$slot[2]],'brand_name'))); ?><div class="part-filters"><label><span class="material-symbols-outlined">filter_list</span><select class="brand-filter" data-target="<?= $slot[2] ?>"><option value="">ทุกยี่ห้อ</option><?php foreach($brands as $brand): ?><option value="<?= htmlspecialchars($brand) ?>"><?= htmlspecialchars($brand) ?></option><?php endforeach; ?></select></label><?php if($slot[2]==='motherboard'): ?><span class="socket-hint">เลือก CPU เพื่อกรอง Socket อัตโนมัติ</span><?php endif; ?></div><div class="part-options" data-group="<?= $slot[2] ?>"><?php foreach($groups[$slot[2]] as $part): ?><?php $partReady=!empty($part['median']) && (int)($part['valid_sample_size']??0)>0 && (int)($part['accepted_observation_count']??0)>0; ?><label class="part-option <?= $partReady?'':'disabled-panel' ?>" data-brand="<?= htmlspecialchars($part['brand_name']) ?>" data-socket="<?= htmlspecialchars($part['socket']??'') ?>"><input type="radio" name="parts[<?= $slot[2] ?>]" value="<?= (int)$part['id'] ?>" <?= $partReady?'':'disabled' ?> data-name="<?= htmlspecialchars($part['full_name']) ?>" data-category="<?= $slot[1] ?>" data-price="<?= $partReady?(float)$part['median']:0 ?>" data-low="<?= $partReady?(float)$part['q1']:0 ?>" data-high="<?= $partReady?(float)$part['q3']:0 ?>" data-socket="<?= htmlspecialchars($part['socket']??'') ?>"><span class="part-radio"></span><span class="part-image"><img src="<?= $base ?>/<?= htmlspecialchars($part['image_path']??'assets/images/admin-5.jpg') ?>" alt="<?= htmlspecialchars($part['full_name']) ?>"><i><?= htmlspecialchars(substr($part['brand_name'],0,2)) ?></i></span><span class="part-name"><span class="brand-name"><?= htmlspecialchars($part['brand_name']) ?></span><b><?= htmlspecialchars($part['full_name']) ?></b><small><?= htmlspecialchars(implode(' · ',array_filter([$part['socket']??null,$part['chipset']??null,$part['memory_type']??null,$part['form_factor']??null]))) ?></small><em><?= $partReady ? 'ความมั่นใจ '.number_format((float)$part['confidence_score']).'% · ข้อมูล '.(int)$part['valid_sample_size'].' รายการ' : 'ข้อมูลตลาดยังไม่เพียงพอ' ?></em></span><span class="part-price"><b><?= $partReady?'฿'.number_format((float)$part['median']):'-' ?></b><small><?= $partReady?'฿'.number_format((float)$part['q1']).'–฿'.number_format((float)$part['q3']):'รอข้อมูลที่ตรวจแล้ว' ?></small></span></label><?php endforeach; ?></div>
<?php else: ?><div class="unavailable-slot"><span class="material-symbols-outlined">database</span><div><b>ฐานข้อมูลราคายังไม่ครอบคลุมหมวดนี้</b><p>ระบบจะกันงบคงเหลือไว้ โดยไม่สร้างรุ่นหรือราคาปลอม</p></div></div><?php endif; ?></section><?php endforeach; ?>
</main>
<aside class="spec-summary card"><span class="meta">YOUR BUILD</span><h2>สรุปสเปก</h2><div id="selected-parts"><div class="summary-empty">ยังไม่ได้เลือกชิ้นส่วน</div></div><div class="summary-money"><div><span>ราคาต่ำ</span><b id="summary-low">฿0</b></div><div class="primary-total"><span>ราคาคาดการณ์</span><b id="summary-total">฿0</b></div><div><span>ราคาสูง</span><b id="summary-high">฿0</b></div><div><span>งบคงเหลือ</span><b id="summary-remaining">฿25,000</b></div></div><div id="budget-state" class="budget-state ok"><span class="material-symbols-outlined">check_circle</span><span>อยู่ในงบประมาณ</span></div><button type="submit"><span class="material-symbols-outlined">save</span> บันทึกและวิเคราะห์สเปก</button><p>ระบบจะตรวจ compatibility เบื้องต้นและบันทึกผลลัพธ์เป็น URL สำหรับแชร์</p></aside>
</div></form>
<?php endif; ?></section>
